server:
  port: 8095

spring:
  application:
    name: manageapp
  datasource:
    driver-class-name: org.postgresql.Driver
    password: password
    username: postgres
    url: jdbc:postgresql://localhost:5453/manageapp
  jpa:
    database: postgresql
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

feign:
  client:
    config:
      default:
        connectTimeout: 15000
        readTimeout: 1000000
        loggerLevel: basic

integrations:
  connect-timeout: 20000
  read-timeout: 1000000
  write-timeout: 5000
  openai-api:
    url: https://api.openai.com/v1/
  hh-api:
    url: https://api.hh.ru/

locale:
  tag: ru-RU
